### ISSUE TITLE
Tag a point release?

### ISSUE THREAD

**Issue by andybalholm** [anacrolix/fuse#9]
On the latest tagged release (0.3.0), build is broken for Linux, and I think for FreeBSD too. It's fixed at the tip of the master branch. It would probably be a good idea to tag version 0.3.1 so that people installing with `go get` without specifying a version will get a version that works.

**Comment by anacrolix** [comment]
Okay I've pushed v0.4.0.

**Comment by anacrolix** [comment]
I pushed v0.3.1 instead. There's no new features, just lots of fixes.

**Comment by poolpOrg** [comment]
Hello,

Just so you know, because https://pkg.go.dev/github.com/anacrolix/fuse?tab=versions caught your v0.4.0 it creates issues as latest still appears to be v0.4.0 which is now missing :-/

**Comment by anacrolix** [comment]
Ugh, Go package management sucks.

**Comment by poolpOrg** [comment]
I most certainly agree.

I was bitten by this a few weeks ago when I created a test v1.0.0-throwaway tag which got caught by go.dev.

It became our @latest because -throwaway is lexicographically behind -beta and I had to tag a v1.0.1-beta just to be behind again.

I feel your pain 😄

**Comment by anacrolix** [comment]
That's comforting. I and others have written about how Go package management fails when you use it enough. There are plenty of subtle bugs, gotchas, and performance issues.
